
  /**
    * Указывается чувствительная информация специальной категории,
    *//которая не подлежит публикации: Конфигурации из Wallet Tonkeeper, Toncenter и другая.



bot:
  token: 123456 // указать
  username: name // указать

server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:file:./data/db
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

ton:
  api:
    key: 12345 // указать
  wallet: 12345 // указать


